import { useEffect, useState } from "react";
import type { Decision, Optimization, Profile } from "../shared/schemas";

const api = async <T,>(url:string, options:RequestInit={}):Promise<T> => { const r=await fetch(url,{headers:options.body instanceof FormData?undefined:{"Content-Type":"application/json"},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Não foi possível concluir a operação.");return data; };
const emptyProfile:Profile={name:"",title:"",subtitle:"",contact:{email:"",phone:"",linkedin:"",github:"",location:""},summary:"",skills:[],experience:[],education:[],languages:[]};
type Job={id:string;company:string;role:string;text:string;analysis?:Optimization;decisions?:Decision[]};
export default function App(){
  const [step,setStep]=useState(0),[profile,setProfile]=useState<Profile>(emptyProfile),[job,setJob]=useState<Job>({id:"",company:"",role:"",text:""}),[analysis,setAnalysis]=useState<(Optimization&{score?:number})|null>(null),[decisions,setDecisions]=useState<Record<string,boolean>>({}),[status,setStatus]=useState<any>({}),[history,setHistory]=useState<any[]>([]),[busy,setBusy]=useState(""),[error,setError]=useState(""),[files,setFiles]=useState<any[]>([]),[langs,setLangs]=useState<string[]>(["ptbr"]);
  const load=()=>Promise.all([api<Profile>("/api/profile"),api<any>("/api/codex/status"),api<any[]>("/api/jobs")]).then(([p,s,h])=>{setProfile(p);setStatus(s);setHistory(h)}).catch(e=>setError(e.message));
  useEffect(()=>{load()},[]); useEffect(()=>{if(status.loginRunning){const t=setTimeout(()=>api<any>("/api/codex/status").then(setStatus),1500);return()=>clearTimeout(t)}},[status]);
  const work=async(label:string,fn:()=>Promise<void>)=>{setBusy(label);setError("");try{await fn()}catch(e:any){setError(e.message)}finally{setBusy("")}};
  const saveProfile=()=>work("Salvando perfil...",async()=>{await api("/api/profile",{method:"PUT",body:JSON.stringify(profile)});setStep(1)});
  const importFile=async(file:File)=>work("Extraindo arquivo...",async()=>{const form=new FormData();form.append("file",file);const data=await api<{text:string}>("/api/import",{method:"POST",body:form});setJob(j=>({...j,text:data.text}))});
  const saveJob=()=>work("Salvando vaga...",async()=>{const saved=await api<Job>("/api/jobs",{method:"POST",body:JSON.stringify(job)});setJob(saved);setStep(2);await load()});
  const analyze=()=>work("Analisando com Codex...",async()=>{const a=await api<Optimization&{score:number}>(`/api/jobs/${job.id}/analyze`,{method:"POST"});setAnalysis(a);setDecisions(Object.fromEntries(a.suggestions.map(s=>[s.id,false])));setStep(3)});
  const saveReview=()=>work("Salvando revisão...",async()=>{const list=Object.entries(decisions).map(([suggestionId,accepted])=>({suggestionId,accepted}));await api(`/api/jobs/${job.id}/decisions`,{method:"PUT",body:JSON.stringify(list)});setStep(4)});
  const generate=()=>work("Gerando PDFs...",async()=>{const out=await api<{files:any[]}>(`/api/jobs/${job.id}/generate`,{method:"POST",body:JSON.stringify({languages:langs})});setFiles(out.files)});
  const openHistory=(id:string)=>work("Abrindo candidatura...",async()=>{const j=await api<any>(`/api/jobs/${id}`);setJob(j);setAnalysis(j.analysis);setDecisions(Object.fromEntries((j.decisions||[]).map((d:Decision)=>[d.suggestionId,d.accepted])));setFiles([]);setStep(j.analysis?3:2)});
  return <div className="shell"><aside><div className="brand"><span>AI</span><div><strong>encAIxa</strong><small>Seu currículo, na vaga certa</small></div></div><nav>{["Perfil","Vaga","Análise","Revisão","Gerar"].map((x,i)=><button key={x} className={step===i?"active":""} onClick={()=>i<=step&&setStep(i)}><b>{i+1}</b>{x}</button>)}</nav><div className="history"><h3>Histórico</h3>{history.length?history.map(h=><button key={h.id} onClick={()=>openHistory(h.id)}><strong>{h.role}</strong><small>{h.company}</small></button>):<p>Nenhuma candidatura criada.</p>}</div><div className={`codex ${status.authenticated?"ok":""}`}><span></span><div><strong>Codex {status.authenticated?"conectado":"desconectado"}</strong><small>{status.version||"CLI não encontrado"}</small></div></div></aside><main><header><div><p className="eyebrow">encAIxa · ASSISTENTE DE CANDIDATURA</p><h1>{["Seu perfil profissional","Descrição da vaga","Análise de aderência","Revise cada sugestão","Prévia e arquivos finais"][step]}</h1></div><div className="step">Etapa {step+1} de 5</div></header>{error&&<div className="error">{error}<button onClick={()=>setError("")}>×</button></div>}{busy&&<div className="loading"><i></i>{busy}</div>}
  {step===0&&<ProfileStep profile={profile} setProfile={setProfile} onSave={saveProfile}/>} 
  {step===1&&<JobStep job={job} setJob={setJob} onFile={importFile} onSave={saveJob}/>} 
  {step===2&&<AnalysisStep status={status} login={()=>work("Iniciando login...",async()=>{await api("/api/codex/login",{method:"POST"});setStatus(await api("/api/codex/status"))})} job={job} analyze={analyze}/>} 
  {step===3&&analysis&&<ReviewStep analysis={analysis} decisions={decisions} setDecisions={setDecisions} next={saveReview}/>} 
  {step===4&&<GenerateStep job={job} langs={langs} setLangs={setLangs} generate={generate} files={files}/>}</main></div>
}
function ProfileStep({profile,setProfile,onSave}:{profile:Profile;setProfile:(p:Profile)=>void;onSave:()=>void}){
  const set=(key:string,v:string)=>setProfile({...profile,[key]:v}); const contact=(key:string,v:string)=>setProfile({...profile,contact:{...profile.contact,[key]:v}});
  const mutate=(fn:(x:Profile)=>void)=>{const x=structuredClone(profile);fn(x);setProfile(x)};
  return <section className="panel"><div className="grid"><Field label="Nome" value={profile.name} onChange={v=>set("name",v)}/><Field label="Título profissional" value={profile.title} onChange={v=>set("title",v)}/><Field label="E-mail" value={profile.contact.email||""} onChange={v=>contact("email",v)}/><Field label="Telefone" value={profile.contact.phone} onChange={v=>contact("phone",v)}/><Field label="LinkedIn" value={profile.contact.linkedin} onChange={v=>contact("linkedin",v)}/><Field label="GitHub" value={profile.contact.github} onChange={v=>contact("github",v)}/></div><Field area label="Resumo profissional" value={profile.summary} onChange={v=>set("summary",v)}/>
  <Field area label="Competências (uma por linha)" value={profile.skills.join("\n")} onChange={v=>mutate(x=>x.skills=v.split("\n").map(s=>s.trim()).filter(Boolean))}/><h2>Experiências</h2>{profile.experience.map((e,i)=><details key={i} open={i===0}><summary>{e.title} · {e.company}</summary><div className="grid"><Field label="Cargo" value={e.title} onChange={v=>mutate(x=>x.experience[i].title=v)}/><Field label="Empresa" value={e.company} onChange={v=>mutate(x=>x.experience[i].company=v)}/><Field label="Período" value={e.period} onChange={v=>mutate(x=>x.experience[i].period=v)}/></div><Field area label="Resultados (uma linha por item)" value={e.bullets.join("\n")} onChange={v=>mutate(x=>x.experience[i].bullets=v.split("\n").filter(Boolean))}/><button onClick={()=>mutate(x=>{x.experience.splice(i,1)})}>Remover experiência</button></details>)}<button onClick={()=>mutate(x=>x.experience.push({title:"Novo cargo",company:"Empresa",period:"Período",bullets:["Descreva um resultado"]}))}>+ Adicionar experiência</button>
  <h2>Formação</h2>{profile.education.map((e,i)=><div className="grid" key={i}><Field label="Curso" value={e.degree} onChange={v=>mutate(x=>x.education[i].degree=v)}/><Field label="Instituição" value={e.institution} onChange={v=>mutate(x=>x.education[i].institution=v)}/><Field label="Período" value={e.period} onChange={v=>mutate(x=>x.education[i].period=v)}/><Field label="Status" value={e.status||""} onChange={v=>mutate(x=>x.education[i].status=v)}/></div>)}
  <h2>Idiomas</h2>{profile.languages.map((l,i)=><div className="grid" key={i}><Field label="Idioma" value={l.language} onChange={v=>mutate(x=>x.languages[i].language=v)}/><Field label="Nível" value={l.level} onChange={v=>mutate(x=>x.languages[i].level=v)}/></div>)}
  <footer><button className="primary" onClick={onSave}>Salvar e continuar →</button></footer></section>}
function JobStep({job,setJob,onFile,onSave}:any){return <section className="panel"><div className="grid"><Field label="Empresa" value={job.company} onChange={(v:string)=>setJob({...job,company:v})}/><Field label="Cargo" value={job.role} onChange={(v:string)=>setJob({...job,role:v})}/></div><div className="upload"><input type="file" accept=".docx,.pdf,.txt,.md" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/><strong>Importar descrição da vaga</strong><span>DOCX, PDF, TXT ou MD · até 10 MB</span></div><Field area label="Ou cole a descrição completa" value={job.text} onChange={(v:string)=>setJob({...job,text:v})}/><footer><button className="primary" disabled={!job.company||!job.role||job.text.length<20} onClick={onSave}>Salvar vaga e continuar →</button></footer></section>}
function AnalysisStep({status,login,job,analyze}:any){return <section className="panel focus"><div className="heroIcon">✦</div><h2>{status.authenticated?"Tudo pronto para analisar":"Conecte o Codex uma vez"}</h2><p>{status.authenticated?`O perfil será comparado à vaga de ${job.role} na ${job.company}. Nenhum dado-base será alterado.`:"A análise usa sua autenticação local do Codex e envia perfil e vaga ao serviço da OpenAI."}</p>{status.loginOutput&&<pre>{status.loginOutput}</pre>}<button className="primary" onClick={status.authenticated?analyze:login}>{status.authenticated?"Analisar aderência":"Conectar Codex"}</button></section>}
function ReviewStep({analysis,decisions,setDecisions,next}:any){const matched=analysis.requirements.filter((r:any)=>r.matched).length;return <section><div className="score"><strong>{analysis.score??"—"}%</strong><div><h2>Aderência estimada</h2><p>{matched} de {analysis.requirements.length} requisitos possuem evidência.</p></div></div><div className="columns"><div><h2>Sugestões</h2>{analysis.suggestions.map((s:any)=><article className="suggestion" key={s.id}><span className="tag">{s.type}</span><p className="old">{s.original||"Sem texto anterior"}</p><p className="new">{s.proposed}</p><small>{s.reason}<br/>Evidência: {s.evidenceRefs.join("; ")}</small><div><button className={decisions[s.id]===false?"reject":""} onClick={()=>setDecisions({...decisions,[s.id]:false})}>Rejeitar</button><button className={decisions[s.id]===true?"accept":""} onClick={()=>setDecisions({...decisions,[s.id]:true})}>Aceitar</button></div></article>)}</div><aside className="gaps"><h2>Lacunas</h2>{analysis.gaps.length?analysis.gaps.map((g:string)=><p key={g}>⚠ {g}</p>):<p>Nenhuma lacuna explícita encontrada.</p>}<h2>Competências relevantes</h2><div>{analysis.relevantSkills.map((s:string)=><span key={s}>{s}</span>)}</div></aside></div><footer><button className="primary" onClick={next}>Salvar revisão e visualizar →</button></footer></section>}
function GenerateStep({job,langs,setLangs,generate,files}:any){const toggle=(l:string)=>setLangs(langs.includes(l)?langs.filter((x:string)=>x!==l):[...langs,l]);return <section><div className="language"><label><input type="checkbox" checked={langs.includes("ptbr")} onChange={()=>toggle("ptbr")}/> Português</label><label><input type="checkbox" checked={langs.includes("en")} onChange={()=>toggle("en")}/> Inglês</label><button className="primary" disabled={!langs.length} onClick={generate}>Gerar arquivos</button></div><iframe title="Prévia do currículo" src={`/api/jobs/${job.id}/preview/${langs[0]||"ptbr"}`}/>{files.length>0&&<div className="downloads">{files.map((f:any)=><a key={f.name} href={f.url}><strong>↓ {f.name}</strong><span>{f.pages} página(s){f.pages>2?" · revisar tamanho":" · pronto"}</span></a>)}</div>}</section>}
function Field({label,value,onChange,area=false}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean}){return <label className={area?"field wide":"field"}><span>{label}</span>{area?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
